version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USER: ag
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: xyzbank
      MYSQL_ROOT_PASSWORD: ag-root-pass
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      xyzbank:

  xyzbank-api:
    container_name: xyzbank-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/xyzbank
      - spring.datasource.username=ag
      - spring.datasource.password=pass
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      xyzbank:
    restart: on-failure

networks:
  xyzbank:
